### ISSUE TITLE
Where is the VirtualServie  VirtualServiceBuilder class?

### ISSUE THREAD

**Issue by chichaoatabc** [snowdrop/istio-java-api#102]
I cant find VirtualServie  VirtualServiceBuilder class in package me.snowdrop.istio.api.networking.v1beta1. Where are they?

**Comment by metacosm** [comment]
Which version of the API are you using?

**Comment by chichaoatabc** [comment]
I read the source code from master , the VirtualService and VirtualServiceBuilder class is missing in the test/VirtualServiceIT.java or Gateway and GatewayBuilder class in test/GatewayIT.java.  I just want to know how to write these CRD resource class.
