### ISSUE TITLE
About resource "handler"

### ISSUE THREAD

**Issue by Chiarorucs** [snowdrop/istio-java-api#110]
Hey,I have a good news to tell you: the one you're waiting for in issues #98 ,who actually needed it ,is coming! 

I've read the class HandlerTest.java in version 1.6.5-Beta2, but I couldn't find a method to get the existing  "handler" ,like the one to get vitualservice or destinationrule. Is it on the way?

Also, I am conscious of the changes between ver 1.1.1 and ver 1.6.5-Beta2:  I can get destinationrule through istioClient.destinationRule() in ver 1.1.1,but now, I'm wondering which one should I take between istioClient.v1beta1DestinationRule() and istioClient.v1alpha3DestinationRule().

 I'll be looking forward to your reply.Thank you so much!

**Comment by metacosm** [comment]
> Hey,I have a good news to tell you: the one you're waiting for in issues #98 ,who actually needed it ,is coming!
> 
> I've read the class HandlerTest.java in version 1.6.5-Beta2, but I couldn't find a method to get the existing "handler" ,like the one to get vitualservice or destinationrule. Is it on the way?

You're right: I forgot to add the methods to the IstioDsl interface. This should now be fixed.

> 
> Also, I am conscious of the changes between ver 1.1.1 and ver 1.6.5-Beta2: I can get destinationrule through istioClient.destinationRule() in ver 1.1.1,but now, I'm wondering which one should I take between istioClient.v1beta1DestinationRule() and istioClient.v1alpha3DestinationRule().

Whichever suits your needs. `v1alpha3` corresponds to the older version used by networking custom resources in previous Istio versions while `v1beta1` corresponds to the current version.

> 
> I'll be looking forward to your reply.Thank you so much!

You're welcome.
