### ISSUE TITLE
istio.common and istio.model package “me.snowdrop.istio.api” is duplicate

### ISSUE THREAD

**Issue by iwangxiaodong** [snowdrop/istio-java-api#112]
Hello:

  istio.common and istio.model package “me.snowdrop.istio.api” is duplicate

  JDK9+ module system is not supported!!!

Thanks!

@metacosm

**Comment by metacosm** [comment]
@iwangxiaodong Could you elaborate please? How does that manifest?
We made the choice to stay on Java 8 for the moment.

**Comment by iwangxiaodong** [comment]
@metacosm 

Just change package name. 

Keep istio.model package，change istio.common package “me.snowdrop.istio.api” to “me.snowdrop.istio.common.api” ...

compatible JDK8 and JDK9+ (JPMS)

**Comment by metacosm** [comment]
I meant, how does that manifest itself in your code?

**Comment by iwangxiaodong** [comment]
enabled JPMS(module-info.java):

error: module my.module reads package me.snowdrop.istio.api from both istio.common and istio.model

**Comment by iwangxiaodong** [comment]
I will close this issue, waiting for future JDK9+JPMS, your official support.

**Comment by metacosm** [comment]
Let's leave it open to keep it on the radar but it's not currently a priority…

**Comment by iwangxiaodong** [comment]
Sure.

**Comment by Gefuxing** [comment]
哈哈
