### ISSUE TITLE
Istio Security API missing

### ISSUE THREAD

**Issue by paolodedo** [snowdrop/istio-java-api#123]
Hello,

With 1.7.5-Beta1 version, I am not able to manipulate the CRUD operations for RequestAuthentication, PeerAuthentication and AuthorizationPolicy through IstioClient.java object (so basically Istio security entities).
There aren't useful methods in this class, while for example I can manipulate Gateway, Virtual Services, etc.

Thanks.

**Comment by metacosm** [comment]
This should be addressed in the newly released `1.7.5-Beta2`. Let us know if there still are issues. Thanks for the report!

**Comment by paolodedo** [comment]
@metacosm thank you very much!
Unfortunately, I haven't found it in maven repository, even though it is released.

**Comment by metacosm** [comment]
@paolodedo Indeed, seems like something went wrong during the release process… 🤔

**Comment by metacosm** [comment]
I'm releasing it again. Not sure what happened before…

**Comment by metacosm** [comment]
Should be fixed now.

**Comment by paolodedo** [comment]
Still nothing

**Comment by metacosm** [comment]
> @metacosm Still nothing

Hmm, https://oss.sonatype.org/#nexus-search;gav~me.snowdrop~istio-model~~~~kw,versionexpand shows it as available, maybe it hasn't propagated to Maven central yet?
