### ISSUE TITLE
Support for Kubernetes-client 5.x

### ISSUE THREAD

**Issue by FWiesner** [snowdrop/istio-java-api#126]
5.x brings several breaking changes that make istio-java-api incompatible

**Comment by metacosm** [comment]
Hi @FWiesner,
Could you elaborate on why you need support for 5.x?

**Comment by FWiesner** [comment]
@metacosm there are upcoming changes (mainly support for dry runs) in 5.x that we need for our project's operator. As 5.x has no backward-compatibility, all modules we use that depend on the Fabric8 Kubernetes Client have to be upgraded

**Comment by metacosm** [comment]
@FWiesner makes sense. Thank you.

**Comment by metacosm** [comment]
Which version of istio are you using, btw?

**Comment by FWiesner** [comment]
We're on 1.7. We'll uptake latest Istio in a month or two

**Comment by metacosm** [comment]
This is now fixed. Thanks!
