### ISSUE TITLE
VirtualService Uri parameter is not set correctly

### ISSUE THREAD

**Issue by bgokden** [snowdrop/istio-java-api#25]
Hi,

We are having some problem in setting VirtualService uri parameters as in example:

`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/wpcatalog"
    - uri:
        prefix: "/consumercatalog"
    rewrite:
      uri: "/newcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
`
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService

We were using additional parameters to set "prefix: /url", but it is not working on this field.
We are using StringMatch class to create uri. We tried several variations but always failed.

Maybe it is fixed with 0.11 but it is not pushed to maven yet so we didn't tried.

**Comment by geoand** [comment]
@bgokden `0.11` is identical to `0.10` I think with the only change being a bump in the Kubernetes Client and Model

**Comment by metacosm** [comment]
@bgokden I will look at it ASAP

**Comment by metacosm** [comment]
The issue is that the code doesn't know how to deal with `oneof` at the moment. I am going to investigate what can be done.

**Comment by metacosm** [comment]
I think I'm going to have to hand-code `StringMatch` for now…

**Comment by bgokden** [comment]
@metacosm I think you are right, there should only one uri inside httpmatch as in this documentation:
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPMatchRequest

It seems like they have conflicting examples in their documentation.
@ avalcepina

**Comment by metacosm** [comment]
Actually, the example is correct, it's just YAML being YAML… :(

**Comment by metacosm** [comment]
@bgokden do you still require pre-0.8 resources? I'm considering removing them to make things simpler so would appreciate hearing from you on that subject…

**Comment by bgokden** [comment]
@metacosm no, we are not using anything pre-0.8. You can remove them. Thanks 👍

**Comment by metacosm** [comment]
Thanks!
