### ISSUE TITLE
Add support for ISTIO_MUTUAL in TLSmode

### ISSUE THREAD

**Issue by puneetsar** [snowdrop/istio-java-api#30]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSSettings-TLSmode

**Comment by geoand** [comment]
I think this is pretty much part of #28.

**Comment by metacosm** [comment]
Fixed by https://github.com/snowdrop/istio-java-api/pull/36/commits/39bcf9c9795b4241b0fbc8bbaa0af9b02d9a5e38
