### ISSUE TITLE
Unable to delete custom resources

### ISSUE THREAD

**Issue by geoand** [snowdrop/istio-java-api#31]
When running some [Istio tests](https://github.com/snowdrop/spring-boot-istio-routing-booster/blob/maistra/tests/src/test/java/me/snowdrop/booster/istio/routing/OpenshiftIT.java), I ran into an issue where I can't seem to delete custom resources.

The custom resources being used are VirtualService, Gateway and DestinationRule and while debugging the IstioClient does return `true` when `deleteCustomResources` is called, although no actual deletion is being performed.

I should add that deleting the resources from the command line does work for me (`oc delete  gateway client-gateway`) and I testing against Openshift 3.10 and Istio 1.0

**Comment by geoand** [comment]
This seems to be an issue with the Kubernetes Client (see [this](https://github.com/geoand/k8s-client-customresource-delete) project for a simple demonstration of the problem)

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
See [this](https://github.com/openshift/origin/issues/20891)

**Comment by metacosm** [comment]
This should be addressed in `master` now via #43.

**Comment by metacosm** [comment]
@geoand can you verify that this issue is indeed fixed, please?
