### ISSUE TITLE
When will 1.0.0 get released ?

### ISSUE THREAD

**Issue by hemikak** [snowdrop/istio-java-api#51]
May I know $subject ?

**Comment by metacosm** [comment]
Hi @hemikak, we're targeting to release this week. May I ask what interest you have in this project?

**Comment by hemikak** [comment]
Hi @metacosm ,

Thanks for the info. I am particularly interested in the istio models. Want to generate yaml files using the models.

Regards,
Hemika

**Comment by metacosm** [comment]
`1.0.0` has been released and has been updated to use Istio `1.0.4`.
