### ISSUE TITLE
Conflicting ResourceHandler when two different object kinds exist

### ISSUE THREAD

**Issue by mocenas** [snowdrop/istio-java-api#56]
When trying to load Istio resources from a yaml file that contains an Istio Policy I will receive a following exception:
java.lang.ClassCastException: me.snowdrop.istio.api.authentication.v1alpha1.Policy cannot be cast to io.fabric8.openshift.api.model.v4_0.Policy

Links to [this](https://github.com/fabric8io/kubernetes-client/issues/1313) issue.

**Comment by metacosm** [comment]
This should be fixed now.
