### ISSUE TITLE
When will upgrade to Istio 1.1 ?

### ISSUE THREAD

**Issue by liuht777** [snowdrop/istio-java-api#58]

**Comment by metacosm** [comment]
Going to look at it next week.

**Comment by metacosm** [comment]
Hi @slowboy666, we've released a 1.1.0-Beta2 version which targets Istio 1.1.3. It'd be great if you could take it for a spin and let us know if you have any issues / comments?

**Comment by slowboy666** [comment]
Many Thanks!

**Comment by zhengzepeng** [comment]
> Hi @slowboy666, we've released a 1.1.0-Beta2 version which targets Istio 1.1.3. It'd be great if you could take it for a spin and let us know if you have any issues / comments? /cc @bgokden

cool~thanks
