### ISSUE TITLE
Istio yaml can contain more than one document inside

### ISSUE THREAD

**Issue by lordofthejars** [snowdrop/istio-java-api#6]
Istio yaml can contain more than one document inside. YAML allows defines more than one document in the same file by separating them with `---`.

We need to configure Jackson library to read in that way.

@hemanik can help on this providing some hints on how to do it since she did it in kubernetes client.

**Comment by metacosm** [comment]
@hemanik can you point me to how to implement this, please? I can probably figure it out myself but it'll go faster if you can point me to the appropriate doc / code / direction! ;)

**Comment by metacosm** [comment]
Thanks!
