### ISSUE TITLE
Error while creating VirtualService resource

### ISSUE THREAD

**Issue by naitikdani** [snowdrop/istio-java-api#61]
I am running version 1.1.0 of istio-java-api and get following error while creating VirtualService resource:

Exception in thread "main" java.lang.NoSuchFieldError: _visitables
        at me.snowdrop.istio.api.networking.v1alpha3.VirtualServiceFluentImpl.withMetadata(VirtualServiceFluentImpl.java:72)
        at me.snowdrop.istio.api.networking.v1alpha3.VirtualServiceBuilder.<init>(VirtualServiceBuilder.java:44)
        at me.snowdrop.istio.api.networking.v1alpha3.VirtualServiceBuilder.<init>(VirtualServiceBuilder.java:18)
        at me.snowdrop.istio.api.networking.v1alpha3.VirtualServiceBuilder.<init>(VirtualServiceBuilder.java:15)

Pasting a section of code:
            VirtualService vs = new VirtualServiceBuilder()
                    .withApiVersion("networking.istio.io/v1alpha3")
                    .withKind("VirtualService")
                    .withNewMetadata().withName("reviews-route").endMetadata()
                    .withNewSpec()
                    .addToHosts("reviews.prod.svc.cluster.local")
                    .addToGateways("logforwarding-gateway")

Any idea how to fix this?

**Comment by geoand** [comment]
@iocanel this sounds like something in your wheelhouse :)

**Comment by iocanel** [comment]
@naitikdani: Seems like you are using incompatible versions of `kubernetes-client` and `istio-java-api` can you please provide the exact versions, so that I can verify my suspicion?

**Comment by naitikdani** [comment]
@iocanel, you were right. I changed kubernetes-client version to 4.2.1 and it started working.

**Comment by iocanel** [comment]
Thanks for the feedback!

**Comment by tremaineeto** [comment]
@iocanel I had a similar issue (java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/dsl/base/OperationContext), and your suggestion seemed to have worked. In general, then, should the advice be to simply always insure that the version of our project's kubernetes-client sync exactly with the version in the istio-client?

**Comment by iocanel** [comment]
If not 100% aligned, then major & minor versions.
