### ISSUE TITLE
Error happens when i get destinationRule 

### ISSUE THREAD

**Issue by zhengzepeng** [snowdrop/istio-java-api#62]
> Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.8.4.113:6443/apis/$apiGroupName/$apiGroupVersion/namespaces/default/destinationrules. Message: 404 page not found
.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:347)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:144)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:551)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:65)
	at cn.com.agree.asm.sync.util.manager.ServiceEntryManager.createOrReplaceServiceEntry(ServiceEntryManager.java:26)
	at cn.com.agree.asm.sync.util.manager.ServiceEntryManager.main(ServiceEntryManager.java:40)

Why the url is :

> https://10.8.4.113:6443/apis/$apiGroupName/$apiGroupVersion/namespaces/default/destinationrules

I think the $apiGroupName and the $apiGroupVersion can be replaced by some values,but how?

My Code is :
`

    public class DestinationRuleDemo {
        public static void createOrReplaceServiceEntry() {
            Config config = new ConfigBuilder().build();
            config.setMasterUrl("https://10.8.4.113:6443");
            DefaultIstioClient client = new DefaultIstioClient(config);
            DestinationRuleList list = client.destinationRule().inNamespace("default").list();
            list.getItems().forEach((DestinationRule rule) -> {
                System.out.println(rule);
            });
        }
        public static void main(String[] args) {
            createOrReplaceServiceEntry();
        }
    }
`

My k8s is 1.11.0，and my istio is 1.1.5!Thanks to help！

**Comment by zhengzepeng** [comment]
istio-client version is 1.1.0-Beta2

**Comment by geoand** [comment]
@iocanel @metacosm any ideas?

**Comment by metacosm** [comment]
That looks like a k8s client issue. Let me look into it.

**Comment by zhengzepeng** [comment]
> That looks like a k8s client issue. Let me look into it.

I see the DestinationRuleOperationImpl source code，and i change my example like that :
`

    public class DestinationRuleDemo {
        public static void createOrReplaceServiceEntry() {
            Config config = new ConfigBuilder().build();
            config.setMasterUrl("https://10.8.4.113:6443");
            DefaultIstioClient client = new DefaultIstioClient(config);
            DestinationRuleList list = getDestinationRuleOperation(client).inNamespace("default").list();
            list.getItems().forEach((DestinationRule rule) -> {
                System.out.println(rule.getMetadata().getName());
            });
        }
    
        public static DestinationRuleOperationImpl getDestinationRuleOperation(DefaultIstioClient client) {
            // The Destination item
            DestinationRule destinationRule = new DestinationRule();
            OperationContext context = new OperationContext();
            // set the item ,so the ApiVersionUtil apiGroup and apiVersion can get the real value,so painful
            context = context.withOkhttpClient(client.getHttpClient()).withConfig(client.getConfiguration()).withItem(destinationRule);
            DestinationRuleOperationImpl destinationRuleOperation = new DestinationRuleOperationImpl(context);
            return destinationRuleOperation;
        }
    
        public static void main(String[] args) {
            createOrReplaceServiceEntry();
        }
    }
`

So it can work now~But i think it can change the DestinationRuleOperationImpl like that :
`

    public DestinationRuleOperationImpl(OperationContext context) {
        super(context.withApiGroupName("networking.istio.io").withApiGroupVersion("v1alpha3").withPlural("destinationrules"));
        this.type = DestinationRule.class;
        this.listType = DestinationRuleList.class;
        this.doneableType = DoneableDestinationRule.class;
    }

`

Thanks to help~

**Comment by metacosm** [comment]
@zhengzepeng there is indeed a bug that I'm working on. I hope to have a fix by the end of the day. Thanks a lot for the report and the investigation!

**Comment by metacosm** [comment]
@zhengzepeng I've released a new version of the API which fixes the issue. Thank you again!

**Comment by zhengzepeng** [comment]
@metacosm Thanks! I test the new version and it works good!
