### ISSUE TITLE
Unable to create destinationrule in istio-system namespace

### ISSUE THREAD

**Issue by naitikdani** [snowdrop/istio-java-api#76]
I want to create a destinationrule in istio-system namespace, but it is failing with the following error:

DestinationRule drDefault = new DestinationRuleBuilder()
                .withApiVersion("networking.istio.io/v1alpha3")
                .withKind("DestinationRule")
                .withNewMetadata().withName("default").withNamespace("istio-system")
                .endMetadata()
                .withNewSpec().withHost("*.local")
      .withNewTrafficPolicy().withNewTls().withMode(TLSSettingsMode.ISTIO_MUTUAL).endTls()
                .endTrafficPolicy()
                .endSpec()
                .build();

 "io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:istio-system. Operation namespace:default.

**Comment by metacosm** [comment]
I will take a look ASAP.

**Comment by metacosm** [comment]
Actually, you probably shouldn't be creating things in the `istio-system` namespace.

**Comment by metacosm** [comment]
You're not supposed to create resources in the `istio-system` namespace.
