### ISSUE TITLE
Not compatible with newer fabric8 kubernetes client versions

### ISSUE THREAD

**Issue by sedooe** [snowdrop/istio-java-api#78]
Hi,

I'm using latest version 1.1.0 and it uses the version 4.2.2 of `io.fabric8.kubernetes-client`.

I just upgraded my `io.fabric8.kubernetes-client` dependency from 4.3.1 to 4.5.2 and suddenly started to get `NoClassDefFoundError` for `io.fabric8.kubernetes.api.builder.ValidationUtils` because it's deleted one of the later versions. And all builder classes of istio-java-api uses `validate` method of this `ValidationUtils`.

Would it be possible to have a new release with a newer version of Fabric8 kubernetes client anytime soon?

**Comment by metacosm** [comment]
Hi, I've updated the client to `4.6.2`. For some reason, `4.6.3` is breaking the build so we're investigating what's going on there. Commit is https://github.com/snowdrop/istio-java-api/commit/82917010d9a0e6ea49a9cbf8a9c43507fb6e8e58 if you want to give it a try.

**Comment by metacosm** [comment]
@sedooe Can I close this issue?

**Comment by sedooe** [comment]
@metacosm sure.
