### ISSUE TITLE
Can not Use EnvoyFilter

### ISSUE THREAD

**Issue by zhengzepeng** [snowdrop/istio-java-api#99]
EnvoyFilter_Patch.Value is Struct in Golang~But in Java，it has problem！

- In Istio

It use yaml to submit the envoyfilter,the patch.Value type like map,Istiod decode it to Struct.

- In Java

when you list EnvoyFilter,the patch.Value type  you get from the apiserver  is like map,so it can not use the json to transfer to struct.

- when you generate the istio-schema.json file
It is a good way to use the java and generate java class.But EnvoyFilter_Patch.Value is Struct type in grpc,so when you generate EnvoyFilter_Patch.Value ,it can be Struct in Java too,so it has the problem what i mentioned before.

I think it is a good way after you generate Schema,you has the chance to change the Schema,like that:

Define the handler:

	type AfterUpdateJSONObjectDescriptor func(desc *JSONObjectDescriptor) (*JSONObjectDescriptor, error)

	var afterUpdateHandlers map[string]AfterUpdateJSONObjectDescriptor = make(map[string]AfterUpdateJSONObjectDescriptor)

	func RegisterAfterUpdateHandler(name string, update AfterUpdateJSONObjectDescriptor) {
		afterUpdateHandlers[name] = update
	}

	func AfterUpdate(name string, desc *JSONObjectDescriptor) (*JSONObjectDescriptor, error) {
		handler, ok := afterUpdateHandlers[name]
		if !ok {
			return desc, nil
		}
		return handler(desc)
	}

change the Schema:

	func (g *schemaGenerator) generate(t reflect.Type, strict bool) (*JSONSchema, error) {
	if t.Kind() != reflect.Struct {
		return nil, fmt.Errorf("only struct types can be converted")
	}

	s := JSONSchema{
		ID:     "http://snowdrop.me/istio/v1/" + t.Name() + "#",
		Schema: "http://json-schema.org/schema#",
		JSONDescriptor: JSONDescriptor{
			Type: "object",
		},
	}
	s.JSONObjectDescriptor = g.generateObjectDescriptor(t)
	if len(g.types) > 0 {
		s.Definitions = make(map[string]JSONPropertyDescriptor)

		for k, v := range g.types {
			name := g.qualifiedName(k)
                       // have the chance to change the JSONPropertyDescriptor
			v, _ := AfterUpdate(name, v)

			descriptor := &JSONDescriptor{
				Type: "object",
			}

			interfaceName := getQualifiedInterfaceName(k)
			i, ok := g.interfacesImpls[interfaceName]
			if ok {
				descriptor.JavaInterfaces = []string{i}
			}

			value := JSONPropertyDescriptor{
				JSONDescriptor:       descriptor,
				JSONObjectDescriptor: v,
				JavaTypeDescriptor: &JavaTypeDescriptor{
					JavaType: g.javaType(k),
				},
			}
			s.Definitions[name] = value
		}
	}
        ....

Register the handler:

	func init() {
		RegisterAfterUpdateHandler("istio_networking_v1alpha3_EnvoyFilter_Patch", update)
	}

	func update(desc *JSONObjectDescriptor) (*JSONObjectDescriptor, error) {
		valueDesc, ok := desc.Properties["value"]
		if !ok {
			return desc, nil
		}
		// JSONReferenceDescriptor
		valueDesc.JSONReferenceDescriptor = nil
		valueDesc.JavaTypeDescriptor = &JavaTypeDescriptor{
			ExistingJavaType: "java.util.Map<String,Object>",
		}

		desc.Properties["value"] = valueDesc
		return desc, nil
	}

So I have the chance to update some wrong type.

**Comment by metacosm** [comment]
This idea is interesting but I think it would be better if we could address the issue directly in the code generation itself instead of relying on modifying said code generation… I'm not sure exactly how to deal with this, though.

Could you please describe in greater detail your use case? It would be helpful to have code example of how the API currently behave and how you would like it to behave, ideally.

**Comment by metacosm** [comment]
Also, could you please specify which version of Istio and which version of `istio-java-api` you're using?

**Comment by zhengzepeng** [comment]
> Also, could you please specify which version of Istio and which version of `istio-java-api` you're using?

The Istio Version is 1.5.4,and the api version is 1.5.5,the demo code like that :

	package istio;

	import io.fabric8.kubernetes.client.Config;
	import io.fabric8.kubernetes.client.ConfigBuilder;
	import me.snowdrop.istio.client.DefaultIstioClient;

	public class IstioDemo {

	    public static void main(String[] args) {
	        Config config = new ConfigBuilder().build();
	        config.setMasterUrl("https://<ip>:<port>");
	        DefaultIstioClient client = new DefaultIstioClient(config);
	        client.v1alpha3EnvoyFilter().inNamespace("istio-system").list();
	    }
	}

I had submit some EnvoyFilters into Istio before.

Running the example code,you will find two problems.

1.unknow field 'context'

	Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
		at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
		at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
		at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:248)
		at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:199)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
		at istio.IstioDemo.createOrReplaceServiceEntry(IstioDemo.java:13)
		at istio.IstioDemo.main(IstioDemo.java:17)
	Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unknown field 'context' (through reference chain: me.snowdrop.istio.api.networking.v1alpha3.EnvoyFilterList["items"]->java.util.ArrayList[0]->me.snowdrop.istio.api.networking.v1alpha3.EnvoyFilter["spec"]->me.snowdrop.istio.api.networking.v1alpha3.EnvoyFilterSpec["configPatches"]->java.util.ArrayList[0]->me.snowdrop.istio.api.networking.v1alpha3.EnvoyConfigObjectPatch["match"])
		at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
		at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3259)
		at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:246)
		... 9 more
	Caused by: java.lang.IllegalArgumentException: Unknown field 'context'
		at me.snowdrop.istio.api.internal.ClassWithInterfaceFieldsRegistry.getFieldInfo(ClassWithInterfaceFieldsRegistry.java:115)
		at me.snowdrop.istio.api.internal.ClassWithInterfaceFieldsDeserializer.deserialize(ClassWithInterfaceFieldsDeserializer.java:78)
		at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
		... 28 more

Because the classes-with-interface-fields.yaml doesn't defind the context type:

	....
	- class: me.snowdrop.istio.api.networking.v1alpha3.EnvoyConfigObjectMatch
	  fields:
	    listener: isEnvoyFilter_EnvoyConfigObjectMatch_ObjectTypes
	    routeConfiguration: isEnvoyFilter_EnvoyConfigObjectMatch_ObjectTypes
	    cluster: isEnvoyFilter_EnvoyConfigObjectMatch_ObjectTypes
	....

2.what i mentioned before

**Comment by zhengzepeng** [comment]
I search the istio doc，only one using the Struct type，[EnvoyFilter-Patch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch)，so can we code like that?

	case reflect.Struct:
		// if Istio Struct type
		if g.qualifiedName(t) == "protobuf_types_Struct" {
			return JSONPropertyDescriptor{
				JavaTypeDescriptor: &JavaTypeDescriptor{
					ExistingJavaType: "java.util.Map<String,Object>",
				},
			}
		}
		definedType, ok := g.types[t]
		if !ok {
			g.types[t] = &JSONObjectDescriptor{}
			definedType = g.generateObjectDescriptor(t)
			g.types[t] = definedType
		}
		return JSONPropertyDescriptor{
			JSONReferenceDescriptor: &JSONReferenceDescriptor{
				Reference: g.generateReference(t),
			},
			JavaTypeDescriptor: &JavaTypeDescriptor{
				JavaType: g.javaType(t),
			},
		}

Seens not a good way to solve the problem，haha

**Comment by metacosm** [comment]
Can you try with the latest version of the API, please?

**Comment by zhengzepeng** [comment]
> Can you try with the latest version of the API, please?

Same problem in 1.6.2-Alpha1/1.6.3-Beta1.

**Comment by metacosm** [comment]
@zhengzepeng can you provide a sample YAML file that exhibits the issue, please, so that I can try to reproduce it locally?

**Comment by zhengzepeng** [comment]
> @zhengzepeng can you provide a sample YAML file that exhibits the issue, please, so that I can try to reproduce it locally?

Sorry, I have been a little busy recently. I forgot to reply to you！

I use istio1.6.2！And some EnvoyFilter exists in the istio-system namespaces,like that:

	[root@k8smaster ~]# kubectl get envoyfilter -n istio-system
	NAME                        AGE
	metadata-exchange-1.4       7d21h
	metadata-exchange-1.5       7d21h
	metadata-exchange-1.6       7d21h
	stats-filter-1.4            7d21h
	stats-filter-1.5            7d21h
	stats-filter-1.6            7d21h
	tcp-metadata-exchange-1.5   7d21h
	tcp-metadata-exchange-1.6   7d21h
	tcp-stats-filter-1.5        7d21h
	tcp-stats-filter-1.6        7d21h

now print the stats-filter-1.6 envoyfilter :

	[root@k8smaster ~]# kubectl get envoyfilter -n istio-system stats-filter-1.6 -o yaml
	apiVersion: networking.istio.io/v1alpha3
	kind: EnvoyFilter
	metadata:
	  annotations:
	    kubectl.kubernetes.io/last-applied-configuration: |
	      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"installed-state","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.2"},"name":"stats-filter-1.6","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"HTTP_FILTER","match":{"context":"SIDECAR_OUTBOUND","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager","subFilter":{"name":"envoy.router"}}}},"proxy":{"proxyVersion":"^1\\.6.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.stats","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":"{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n","root_id":"stats_outbound","vm_config":{"code":{"local":{"inline_string":"envoy.wasm.stats"}},"runtime":"envoy.wasm.runtime.null","vm_id":"stats_outbound"}}}}}}},{"applyTo":"HTTP_FILTER","match":{"context":"SIDECAR_INBOUND","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager","subFilter":{"name":"envoy.router"}}}},"proxy":{"proxyVersion":"^1\\.6.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.stats","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":"{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n","root_id":"stats_inbound","vm_config":{"code":{"local":{"inline_string":"envoy.wasm.stats"}},"runtime":"envoy.wasm.runtime.null","vm_id":"stats_inbound"}}}}}}},{"applyTo":"HTTP_FILTER","match":{"context":"GATEWAY","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager","subFilter":{"name":"envoy.router"}}}},"proxy":{"proxyVersion":"^1\\.6.*"}},"patch":{"operation":"INSERT_BEFORE","value":{"name":"istio.stats","typed_config":{"@type":"type.googleapis.com/udpa.type.v1.TypedStruct","type_url":"type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm","value":{"config":{"configuration":"{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\",\n  \"disable_host_header_fallback\": true\n}\n","root_id":"stats_outbound","vm_config":{"code":{"local":{"inline_string":"envoy.wasm.stats"}},"runtime":"envoy.wasm.runtime.null","vm_id":"stats_outbound"}}}}}}}]}}
	  creationTimestamp: "2020-07-15T09:10:54Z"
	  generation: 1
	  labels:
	    install.operator.istio.io/owning-resource: installed-state
	    istio.io/rev: default
	    operator.istio.io/component: Pilot
	    operator.istio.io/managed: Reconcile
	    operator.istio.io/version: 1.6.2
	  name: stats-filter-1.6
	  namespace: istio-system
	  resourceVersion: "8134330"
	  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters/stats-filter-1.6
	  uid: fd501ef9-f512-403f-9ce9-1c790d760b70
	spec:
	  configPatches:
	  - applyTo: HTTP_FILTER
	    match:
	      context: SIDECAR_OUTBOUND
	      listener:
	        filterChain:
	          filter:
	            name: envoy.http_connection_manager
	            subFilter:
	              name: envoy.router
	      proxy:
	        proxyVersion: ^1\.6.*
	    patch:
	      operation: INSERT_BEFORE
	      value:
	        name: istio.stats
	        typed_config:
	          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
	          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
	          value:
	            config:
	              configuration: |
	                {
	                  "debug": "false",
	                  "stat_prefix": "istio"
	                }
	              root_id: stats_outbound
	              vm_config:
	                code:
	                  local:
	                    inline_string: envoy.wasm.stats
	                runtime: envoy.wasm.runtime.null
	                vm_id: stats_outbound
	  - applyTo: HTTP_FILTER
	    match:
	      context: SIDECAR_INBOUND
	      listener:
	        filterChain:
	          filter:
	            name: envoy.http_connection_manager
	            subFilter:
	              name: envoy.router
	      proxy:
	        proxyVersion: ^1\.6.*
	    patch:
	      operation: INSERT_BEFORE
	      value:
	        name: istio.stats
	        typed_config:
	          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
	          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
	          value:
	            config:
	              configuration: |
	                {
	                  "debug": "false",
	                  "stat_prefix": "istio"
	                }
	              root_id: stats_inbound
	              vm_config:
	                code:
	                  local:
	                    inline_string: envoy.wasm.stats
	                runtime: envoy.wasm.runtime.null
	                vm_id: stats_inbound
	  - applyTo: HTTP_FILTER
	    match:
	      context: GATEWAY
	      listener:
	        filterChain:
	          filter:
	            name: envoy.http_connection_manager
	            subFilter:
	              name: envoy.router
	      proxy:
	        proxyVersion: ^1\.6.*
	    patch:
	      operation: INSERT_BEFORE
	      value:
	        name: istio.stats
	        typed_config:
	          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
	          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
	          value:
	            config:
	              configuration: |
	                {
	                  "debug": "false",
	                  "stat_prefix": "istio",
	                  "disable_host_header_fallback": true
	                }
	              root_id: stats_outbound
	              vm_config:
	                code:
	                  local:
	                    inline_string: envoy.wasm.stats
	                runtime: envoy.wasm.runtime.null
	                vm_id: stats_outbound

so you just need to list the envoyfilter in the istio-system namespace:

	import io.fabric8.kubernetes.client.Config;
	import io.fabric8.kubernetes.client.ConfigBuilder;
	import me.snowdrop.istio.client.DefaultIstioClient;

	public class IstioDemo {

	    public static void main(String[] args) {
	        Config config = new ConfigBuilder().build();
	        config.setMasterUrl("https://<ip>:<port>");
	        DefaultIstioClient client = new DefaultIstioClient(config);
	        client.v1alpha3EnvoyFilter().inNamespace("istio-system").list();
	    }
	}

and it will show you the problem

**Comment by metacosm** [comment]
@zhengzepeng this should now be fixed in 1.6.5-Beta4. See https://github.com/snowdrop/istio-java-api/blob/master/istio-model/src/test/java/me/snowdrop/istio/api/networking/v1alpha3/EnvoyFilterTest.java how to access the `EnvoyFilter` data in a detyped way.

**Comment by zhengzepeng** [comment]
@metacosm Thanks!But it was builded in java 11,can u release a version builded in java8?we use this in java8,it is unlikely to upgrade to java 11 for now

**Comment by metacosm** [comment]
@zhengzepeng I've released a new version built using Java 8.

**Comment by zhengzepeng** [comment]
> @zhengzepeng I've released a new version built using Java 8.

Thank you!
